# Generated by Django 4.0.1 on 2022-01-13 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_photo_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photo_tags', to='shared_photo_library.Tag'),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100)),
                ('conjunctive', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(default=True)),
                ('location_rect', models.CharField(max_length=100, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_users', models.ManyToManyField(related_name='view_shared_with', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='view_tags', to='shared_photo_library.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_users', models.ManyToManyField(related_name='col_shared_with', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(to='shared_photo_library.View')),
            ],
        ),
    ]
