# Generated by Django 4.0.1 on 2022-01-14 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_photo_library', '0002_remove_tag_photo_photo_tags_view_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('conjunctive', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(default=True)),
                ('location_rect', models.CharField(max_length=100, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_users', models.ManyToManyField(related_name='view_shared_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='view',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='view',
            name='shared_users',
        ),
        migrations.RemoveField(
            model_name='view',
            name='tags',
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.AlterField(
            model_name='collection',
            name='views',
            field=models.ManyToManyField(to='shared_photo_library.FilterView'),
        ),
    ]
