# Generated by Django 4.0.1 on 2022-01-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
