# Generated by Django 4.0.1 on 2022-01-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0006_alter_photo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover',
            field=models.ImageField(default='empty_col.jpg', upload_to=''),
        ),
    ]
