# Generated by Django 4.0.1 on 2022-01-15 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_photo_library', '0009_photo_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='shared_users',
            field=models.ManyToManyField(related_query_name='col_shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
