# Generated by Django 4.0.1 on 2022-01-15 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0010_alter_collection_shared_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
