# Generated by Django 4.0.1 on 2022-01-16 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared_photo_library', '0012_alter_collection_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
