# Generated by Django 4.0.1 on 2022-01-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0013_alter_collection_shared_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='views',
        ),
        migrations.AddField(
            model_name='filterview',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attached_to', to='shared_photo_library.collection'),
            preserve_default=False,
        ),
    ]
