# Generated by Django 4.0.1 on 2022-01-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0015_alter_filterview_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterview',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='filterview',
            name='start_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
