# Generated by Django 4.0.1 on 2022-01-16 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0016_alter_filterview_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterview',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='filterview',
            name='photos',
            field=models.ManyToManyField(related_name='view_photos', to='shared_photo_library.Photo'),
        ),
    ]
