# Generated by Django 4.0.1 on 2022-01-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_photo_library', '0017_filterview_created_date_filterview_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterview',
            name='cover',
            field=models.ImageField(default='empty_col.jpg', upload_to=''),
        ),
    ]
